<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>4fce6657-fc4c-4765-bd69-d382ca002ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.flex-next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slider_item_big_top']/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4b5b7d0-abf1-4896-afdd-67146d7faf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-next</value>
      <webElementGuid>b71b9597-4033-427e-b555-f4c712bd4746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ffb542ad-7cb3-48a4-bc57-a8f9f1e2ef14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>6a35d9e1-5b88-45d5-9bef-82f76c811e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider_item_big_top&quot;)/div[@class=&quot;flexslider&quot;]/ul[@class=&quot;flex-direction-nav&quot;]/li[@class=&quot;flex-nav-next&quot;]/a[@class=&quot;flex-next&quot;]</value>
      <webElementGuid>18b1aa2c-0471-461a-9186-e4a2dbc84088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider_item_big_top']/div/ul/li[2]/a</value>
      <webElementGuid>54d713a1-46e7-4724-9811-62cf4443dc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next')]</value>
      <webElementGuid>8c2ae023-1eac-4b02-96be-d5a3ca8addec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[31]</value>
      <webElementGuid>0fec10c0-9046-4bdd-a289-74ebd4471587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>58ecece5-c7d6-48ba-aa50-f621e9ca25b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>8c5bdbab-54a1-4769-98ce-234033c9bbca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
