<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thot</name>
   <tag></tag>
   <elementGuidId>26375abd-21b3-40ad-bcd0-ed7614a08686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v3_header']/div[2]/div[3]/div/div[3]/div/div[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b8ee131-a607-47a8-9f5b-138b16bb832a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hasaki.vn/customer/account/logout/</value>
      <webElementGuid>70ec8c28-f5fb-41d6-a2f3-eeaf41c60a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>9055b0ae-440b-479c-9ff2-81a98e14678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thoát</value>
      <webElementGuid>d76b348f-1382-4fb4-9bc4-7a97bc473502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v3_inf_right_header&quot;]/div[@class=&quot;item_header item_login user_login&quot;]/div[@class=&quot;sub_login sub_dalogin&quot;]/div[@class=&quot;main_content_sub_login&quot;]/div[@class=&quot;item_da_login&quot;]/a[1]</value>
      <webElementGuid>a023b569-389d-4ba2-a734-fc47647b2830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/div[3]/div/div[5]/a</value>
      <webElementGuid>ff5fdc58-c370-4cef-ac04-7f92c5f11789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thoát')]</value>
      <webElementGuid>de2699e0-9f76-4741-b0fa-2c8b58dea985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hasaki.vn/customer/account/logout/')]</value>
      <webElementGuid>80dc899b-5545-47e2-8c8b-54565642c0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>a7ff1eaf-974e-4ebe-bd15-9f977cbe5d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hasaki.vn/customer/account/logout/' and (text() = ' Thoát' or . = ' Thoát')]</value>
      <webElementGuid>b301d157-4394-4bda-a429-d0a1b26b2bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
