<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Toner</name>
   <tag></tag>
   <elementGuidId>0af1142d-711a-4af7-bd9e-b306491ffdf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_mini_form']/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cc43cae-30c3-4f76-ad0a-c8a89e4289d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hasaki.vn/danh-muc/toner-c1857.html?utm_medium=seo&amp;utm_source=destop_search&amp;utm_campaign=toner_push_29032022</value>
      <webElementGuid>6863662c-121e-424c-8f99-f3b2f6e835bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toner</value>
      <webElementGuid>bc5e31c0-0591-4a78-a119-f4e1f13cb1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_mini_form&quot;)/div[@class=&quot;block_demo_search width_common&quot;]/a[3]</value>
      <webElementGuid>59e81167-8eae-4f5b-860a-9a42209037db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div/a[3]</value>
      <webElementGuid>a89aead3-f974-4987-adb3-f7ad98e614ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Toner')]</value>
      <webElementGuid>48c0a56e-e3d5-4c49-8bec-69613d602224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hasaki.vn/danh-muc/toner-c1857.html?utm_medium=seo&amp;utm_source=destop_search&amp;utm_campaign=toner_push_29032022')]</value>
      <webElementGuid>8c2cfd5e-0257-45e0-9862-f80ca0249101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>0c79729a-e8c2-4cd4-89a9-be106fce61ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hasaki.vn/danh-muc/toner-c1857.html?utm_medium=seo&amp;utm_source=destop_search&amp;utm_campaign=toner_push_29032022' and (text() = 'Toner' or . = 'Toner')]</value>
      <webElementGuid>4691f905-07c7-4414-b2f9-6b6db3862777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
