<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng k</name>
   <tag></tag>
   <elementGuidId>a76e3828-6692-4c20-8729-fc4bf3cf3294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnRegister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnRegister']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca8a9d51-b747-4fda-ac08-6165080b88b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_site_1</value>
      <webElementGuid>8984c58b-0f64-4577-90e2-55b6501b2c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRegister</value>
      <webElementGuid>2fc0f07d-b7b5-415e-9f7d-323c82624484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>e7c75023-9665-47f0-afa3-246b1fd27c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnRegister&quot;)</value>
      <webElementGuid>737667f8-ee59-4c19-8522-9cc85c824063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnRegister']</value>
      <webElementGuid>399dcada-1250-49df-b042-8cfd12f05fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-head-register']/div/button</value>
      <webElementGuid>97b79130-fd20-4ece-96fc-8104bb0c23fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>8a6c60f7-9a10-445d-959c-f9956e7caca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnRegister' and (text() = 'Đăng ký' or . = 'Đăng ký')]</value>
      <webElementGuid>81844163-bc78-49cc-a5eb-83a3f3834f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
