<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ly m</name>
   <tag></tag>
   <elementGuidId>88462864-ef0d-40f7-9abb-0f303ade96ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verifyUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='verifyUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2927872-477f-4ed2-8ba5-b1f146bff338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba99e2e2-538b-414a-abc8-6dd583add753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>handleVerify(this)</value>
      <webElementGuid>6986fb68-4b90-4531-b078-2768402546a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verifyUserName</value>
      <webElementGuid>5108aa63-7644-42b1-91a7-29d42cb3476f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>.showRegisterMessage</value>
      <webElementGuid>f58d9de3-e2d1-4c46-9a2e-cd146bf8a8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>#reg-email</value>
      <webElementGuid>96bbf31e-431d-41c8-ac5b-6d370caeb9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>lấy mã</value>
      <webElementGuid>2afca996-efa7-4b56-bfb4-66e08e798f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifyUserName&quot;)</value>
      <webElementGuid>f99528b0-ece7-4332-a2e8-79b78fccbbf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='verifyUserName']</value>
      <webElementGuid>3afe1c34-18fe-4f7a-b798-1561080c33a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-head-register']/div/div[4]/div/button[2]</value>
      <webElementGuid>b9e13703-a0f3-4809-a6f1-6be243bd145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>fdcbc66b-0dd8-4f24-9e97-aeeafde41539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'verifyUserName' and (text() = 'lấy mã' or . = 'lấy mã')]</value>
      <webElementGuid>16f74ec0-ee96-4c56-a7bd-59d886ceb246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
