<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_text_search</name>
   <tag></tag>
   <elementGuidId>b4fae057-817d-4cb1-b6b1-563f978fad2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_mini_form_mb']/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1416a4b3-6794-485c-a2aa-f0e721e72a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_search</value>
      <webElementGuid>8aba033b-bb84-4dd8-971e-de6a65bd1360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_mini_form_mb&quot;)/div[@class=&quot;block_search_mobile&quot;]/a[@class=&quot;show_search&quot;]/div[@class=&quot;text_search&quot;]</value>
      <webElementGuid>030bbab3-1f58-4aea-b052-c761d7005365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form_mb']/div/a/div</value>
      <webElementGuid>2f395a5f-f466-45ca-ae27-b729e4e7eda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>cb15ac8b-b340-4f1e-95f9-6582d13930e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
