<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_loading_1</name>
   <tag></tag>
   <elementGuidId>dedcfea9-1903-43e7-a3ae-2d9d19f3fb96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.login-facebook > img.loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='https://hasaki.vn/images/graphics/img_login_fb.jpg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cb000f1b-93b8-472e-a959-463e321288fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hasaki.vn/images/graphics/img_login_fb.jpg</value>
      <webElementGuid>5c4d3ef2-f7fb-4400-930b-0dd26a14832c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>7432c1f7-39d0-464e-92ed-90f7533d4502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11c6b822-e667-4925-b6cd-e3dacfab288a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v3_inf_right_header&quot;]/div[@class=&quot;item_header item_login&quot;]/div[@class=&quot;sub_login&quot;]/div[@class=&quot;main_content_sub_login&quot;]/div[@class=&quot;block_login_fb&quot;]/a[@class=&quot;login-facebook&quot;]/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>4738a9e2-011d-43fb-8de7-282971f8df82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/div[3]/div/div/a/img</value>
      <webElementGuid>13a0dc4b-d93b-430e-983f-e8cf34ffa62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/images/graphics/img_login_fb.jpg')]</value>
      <webElementGuid>ddc2feff-0a47-41b1-8e62-2eea14e4954f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
      <webElementGuid>672ea99f-3999-49a9-89c6-f67e0ce24932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/images/graphics/img_login_fb.jpg']</value>
      <webElementGuid>bac9a1be-f3cb-4d4a-875f-18f4021ebceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/div[3]/div/div/a[2]/img</value>
      <webElementGuid>660c581d-f378-421a-abb2-2a50231e64a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/images/graphics/img_login_gg.jpg')]</value>
      <webElementGuid>63e07983-f971-4d42-a812-bb846bd86656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>753ddfbd-1a33-492e-8a16-309f1b1206a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/images/graphics/img_login_gg.jpg']</value>
      <webElementGuid>756cab4c-e6b6-4169-8714-8a7f6d12871f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/a/img</value>
      <webElementGuid>0fafc2dc-2913-4bd2-84f4-24906fef383d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/images/graphics/icon_header_2.svg')]</value>
      <webElementGuid>5cc40ce6-3cdc-4b3a-b070-8c883e7ab7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/a/img</value>
      <webElementGuid>cfdbb42f-ba69-4b4d-be47-ebba69dbcb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/images/graphics/icon_header_2.svg']</value>
      <webElementGuid>404e371d-223f-4b68-b40f-7b2a1d4d4ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
