<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__icon_iq4kl_47 loading</name>
   <tag></tag>
   <elementGuidId>001e42ff-4993-4bc5-8968-5da7a0cab114</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hsk-chat-root']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img._icon_iq4kl_47.loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af01de77-93aa-45c1-8c0f-41a7fc5fca7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_icon_iq4kl_47 loading</value>
      <webElementGuid>ca02007a-9322-4e21-b55b-8bec9e512b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://wsc.hasaki.vn/assets/customer_icons/app_icon.svg</value>
      <webElementGuid>468de12f-b3f3-406a-8304-66c413fc7996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>60px</value>
      <webElementGuid>7f6e330a-4f3e-4904-8bc8-60d12e7e399f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>60px</value>
      <webElementGuid>3ac49636-3ad8-4dd8-a862-03791b38cefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3c11c664-89d0-46be-9b37-9a62a144c635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hsk-chat-root&quot;)/img[@class=&quot;_icon_iq4kl_47 loading&quot;]</value>
      <webElementGuid>ac94515e-413a-4f87-aaef-a2468ed442c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hsk-chat-root']/img</value>
      <webElementGuid>8883524a-97d8-492e-943a-06446e11eb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://wsc.hasaki.vn/assets/customer_icons/app_icon.svg')]</value>
      <webElementGuid>d73977ab-9182-4d11-9a4a-06300f1320be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8c45b5ae-8f97-4331-aea1-7462e4b0c768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://wsc.hasaki.vn/assets/customer_icons/app_icon.svg']</value>
      <webElementGuid>55f871c9-6df7-437f-ad61-08882dfd1963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
