<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_loading</name>
   <tag></tag>
   <elementGuidId>142e4ee0-4d91-483e-84bf-229fe5ac608d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.icon_header > img.loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v3_header']/div[2]/div[3]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5998465-d588-4c7c-a48c-1acf5f7e91ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hasaki.vn/images/graphics/icon_header_2.svg</value>
      <webElementGuid>93718241-1d93-4ac5-a1f1-5d55067d1832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>b1681d4b-ad23-4df0-958f-458a5b4b15f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dcafe073-889f-47a3-b109-d93730a3983c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v3_inf_right_header&quot;]/div[@class=&quot;item_header item_login&quot;]/a[@class=&quot;icon_header&quot;]/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>a4f26646-5951-459c-af9a-d36dd79e8822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/a/img</value>
      <webElementGuid>975cc7c8-2c91-49c1-b6e8-17be0e23713a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/images/graphics/icon_header_2.svg')]</value>
      <webElementGuid>05ea4192-bfad-4cec-8cc3-0770eda89c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/a/img</value>
      <webElementGuid>7f181361-3fcc-4bd7-a4bd-78b85972db77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/images/graphics/icon_header_2.svg']</value>
      <webElementGuid>9cf3721c-76a4-41d9-acaa-6b78437b35c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/div[3]/div/div/a/img</value>
      <webElementGuid>d0c42cba-d8b1-419e-9d89-ed822f345279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/images/graphics/img_login_fb.jpg')]</value>
      <webElementGuid>a74ea690-f9c6-4a4b-b757-5f54f8f93482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
      <webElementGuid>7342328d-bf98-4618-a626-90ba07ab6f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/images/graphics/img_login_fb.jpg']</value>
      <webElementGuid>f8638393-58e3-4c06-8164-53663e40a857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart_item_header']/a/img</value>
      <webElementGuid>1150035a-684f-40f6-92ed-8abf8a387810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/wap-static/images/graphics/cart_top.svg')]</value>
      <webElementGuid>f63868bb-57c1-42d0-9545-ed6e94010240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>71877f2d-1790-4b1f-a28a-c4c39f348452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/wap-static/images/graphics/cart_top.svg']</value>
      <webElementGuid>4530221d-8e2e-4b19-ab59-5ff50e7594ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div/a/img</value>
      <webElementGuid>be71ffb2-654a-4e9a-9206-f705f43c761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/v3/images/graphics/logo_site.svg')]</value>
      <webElementGuid>2ac0d753-c659-4823-af2f-28cebb0c72fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>60f404f7-8764-4842-8f8d-0a5b17a72a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/v3/images/graphics/logo_site.svg']</value>
      <webElementGuid>907e5b14-4d0d-4d90-8166-fcaf267731e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
