<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_icon_back loading</name>
   <tag></tag>
   <elementGuidId>4927a1b4-d835-472b-9bc5-15fa4f2c5d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.icon_back.loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_wap']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2e52960e-5b23-496e-a8a5-223385fab243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_back loading</value>
      <webElementGuid>c0db1ee9-1d2a-4f5f-85a1-97fdc07707aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hasaki.vn/wap-static/images/graphics/back_200x200.svg</value>
      <webElementGuid>94a340ab-a0d8-4552-8155-44d2dd4b3a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>506c431b-05bd-42d0-99ad-246ed47411cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_wap&quot;)/a[@class=&quot;logo_site_detail material-ripple&quot;]/img[@class=&quot;icon_back loading&quot;]</value>
      <webElementGuid>92346dd3-5076-4001-8926-2b9f3710b67b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_wap']/a/img</value>
      <webElementGuid>2dbfbb60-808f-4194-99d0-938b7e4dae7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/wap-static/images/graphics/back_200x200.svg')]</value>
      <webElementGuid>ae74b799-2fcf-48b8-877d-01ae17ca4754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>535758cb-1a0a-4ee0-89e4-c2e5c86fc31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/wap-static/images/graphics/back_200x200.svg']</value>
      <webElementGuid>b47f1ca3-2548-488b-9e3f-0c7174cf14f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
