<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputHsk-Search</name>
   <tag></tag>
   <elementGuidId>f8156df8-b746-4ac0-b031-f5b04d9dc901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Hsk-Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Hsk-Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>528ce3bd-1d87-4e8d-bef8-9f3e9226fac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Hsk-Search</value>
      <webElementGuid>acecad18-ade1-41c3-b40d-4b888491ffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bbd977a-0406-41c1-b82a-c5bddb19fae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Giờ hoạt động: 8h - 22h</value>
      <webElementGuid>b5fc1706-4664-4102-990e-0ac86965fa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_base-input_1qm6a_61</value>
      <webElementGuid>ff5ba114-adda-4b05-a48c-07c47bfc089a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Hsk-Search&quot;)</value>
      <webElementGuid>1f283b81-fb27-44af-a056-5f3daa0e1fb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Hsk-Search']</value>
      <webElementGuid>f1c8158a-4dc2-46c2-b575-c476cab5c7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-chat-container']/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>9f265292-e2b7-44f0-b570-e32ba9c68d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>843561c0-3493-486d-8e16-96f1a5fe7a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Hsk-Search' and @type = 'text' and @placeholder = 'Giờ hoạt động: 8h - 22h']</value>
      <webElementGuid>7de47854-0ccc-44d5-aed7-14f0d1d3be22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
