<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_fullname</name>
   <tag></tag>
   <elementGuidId>aea98d65-5f79-4be5-92b1-b5c10846f39e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg-fullname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-fullname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02f3654d-1166-4729-82a1-74c403648af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-fullname</value>
      <webElementGuid>1eb46333-2ee7-4ab9-a649-62f6cc55597e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fullname</value>
      <webElementGuid>e9aa3777-fb3b-413a-8750-65d136f3cea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cee03d3-8a79-40b7-915d-060707543509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Họ tên</value>
      <webElementGuid>ef11071b-10bc-45f7-ba03-bd90a413c006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>03d41c0c-5ebb-455c-bd62-4b93dec5d664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true, 'validate-custom-fullname': true}</value>
      <webElementGuid>3f9e5e9d-8324-48fa-b40f-7b895ea0d10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg-fullname&quot;)</value>
      <webElementGuid>d798f35e-cdb9-4391-87a4-b138b33fde99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-fullname']</value>
      <webElementGuid>c4954c93-f079-479a-99bc-06f3a61bf1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-head-register']/div/div[6]/div/input</value>
      <webElementGuid>4af46d6e-3d8b-4ce5-9ab5-e0960f5d775e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>5e6f8654-9fea-472c-a1de-c1402cbc5393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reg-fullname' and @name = 'fullname' and @type = 'text' and @placeholder = 'Họ tên']</value>
      <webElementGuid>02fddb6a-bbe1-4e6b-85ad-5a9de46074be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
