<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_q</name>
   <tag></tag>
   <elementGuidId>dc374205-7e41-4e80-9c3e-b32ad4dab28e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27df5647-ee5e-44ab-b77d-6e9ca6492af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>753925ca-e714-469e-b781-9fd5710670d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm, thương hiệu bạn mong muốn...</value>
      <webElementGuid>91106d2b-758c-4aad-8545-860b6f1c9c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_search</value>
      <webElementGuid>9ef960ef-1956-401d-b7ac-fe3d89b98dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>d6ca2e57-1b42-4a11-ab9d-cd4c6d337ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-box-parent</name>
      <type>Main</type>
      <value>#block_suggest_search</value>
      <webElementGuid>7d35ea52-36aa-4718-a5e8-b44c893286be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>248c4b4b-a330-45ec-b856-c6fec843979c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ebd7669-e8ae-473d-8888-722af81d19b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>campaign-rel</name>
      <type>Main</type>
      <value>[{&quot;label&quot;:&quot;Deal 1K-4K áp dụng CN141 TP Đà Lạt, Lâm Đồng (20-26/11)&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/khai-truong-chi-nhanh-140-141?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=khai-truong-chi-nhanh-140-141&amp;utm_term=khai-truong-chi-nhanh-140-141_201123&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1701017940,&quot;start_time&quot;:1700413200},{&quot;label&quot;:&quot;Deal 1K-4K áp dụng CN140 TP Vị Thanh, Hậu Giang (20-26/11)&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/khai-truong-chi-nhanh-140-141?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=khai-truong-chi-nhanh-140-141&amp;utm_term=khai-truong-chi-nhanh-140-141_201123&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1701017940,&quot;start_time&quot;:1700413200},{&quot;label&quot;:&quot;Black Friday Voucher Hot 24K (Áp dụng 21-26/11)&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/best-seller?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=black-friday&amp;utm_term=black-friday_211123&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1701017940,&quot;start_time&quot;:1700499600},{&quot;label&quot;:&quot;Maybelline Mua 1 Tặng 1 (20-27/11)&quot;,&quot;url&quot;:&quot;https://hasaki.vn/thuong-hieu/maybelline.html?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=maybelline-mua-1-tang-1&amp;utm_term=maybelline-mua-1-tang-1_201123&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1701104340,&quot;start_time&quot;:1700413200},{&quot;label&quot;:&quot;Deal Hot Giảm Hơn 60% DV Trải Nghiệm: Triệt Lông, Trị Mụn, Trị Sẹo Rỗ, Peel, Trẻ Hóa Da&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/trai-nghiem-dich-vu?utm_source=website&amp;utm_medium=keyword_thanh_search&amp;utm_campaign=trai-nghiem-dich-vu&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1700585940,&quot;start_time&quot;:1699203600}]</value>
      <webElementGuid>8641fbfd-bf39-4484-a593-dd9dcddf1ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)</value>
      <webElementGuid>b4f17509-4809-4fb1-be44-aeba44a36bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search']</value>
      <webElementGuid>7362b777-8d74-435e-a2b4-d36772354da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div[2]/div/div/div/input</value>
      <webElementGuid>ef170771-968c-4fe9-a857-30446562f10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>b8f12139-077a-4452-8915-b63f76d28739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @placeholder = 'Tìm sản phẩm, thương hiệu bạn mong muốn...' and @name = 'q']</value>
      <webElementGuid>f306c417-92c8-49cc-9a97-220841767279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
