<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Toner cho da du mun</name>
   <tag></tag>
   <elementGuidId>d805acac-d3ea-4d9b-b3e0-fdfd700d04fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='base-textarea-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#base-textarea-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03494923-b3a1-4df4-82bb-6a1030b4f595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base-textarea-id</value>
      <webElementGuid>c68ef3aa-6a27-46ee-842c-cc2407063255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>6f75d836-62ec-4dec-89f1-fc2eeceb8702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập nội dung tin nhắn...</value>
      <webElementGuid>d76272ff-9893-4854-9b0a-b77f8fc6dcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_tara_tcezg_6</value>
      <webElementGuid>be9fdb44-d88b-4e95-aa02-1ab463fba800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toner cho da dầu mun</value>
      <webElementGuid>a4d7da6e-a70a-4436-b3ad-767d26e028c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-textarea-id&quot;)</value>
      <webElementGuid>abfafd74-9763-4d39-a02c-a42386903529</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='base-textarea-id']</value>
      <webElementGuid>1f4b8651-bcfc-4994-ac3b-00a5185ef3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chatSceneContainer']/div[2]/div/div/div/textarea</value>
      <webElementGuid>07759067-bd94-45ac-82cd-97b23b853e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>83e85d35-8775-464d-801a-65b2e5ee9f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'base-textarea-id' and @placeholder = 'Nhập nội dung tin nhắn...' and (text() = 'Toner cho da dầu mun' or . = 'Toner cho da dầu mun')]</value>
      <webElementGuid>76f857e8-d81a-40df-86e4-935775b3d5a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
