<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Toner cho da d_1_2</name>
   <tag></tag>
   <elementGuidId>d637cf64-88a6-43a8-ac7f-f25efb5e16aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='base-textarea-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#base-textarea-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>08dff8a6-4eed-4c97-b62d-7d39456b55d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base-textarea-id</value>
      <webElementGuid>03625aeb-320b-4c02-99e9-01f471429473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>3935da69-25dd-4767-9bd1-d01c85365aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập nội dung tin nhắn...</value>
      <webElementGuid>c67eab3d-0674-4060-9b57-068907e36b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_tara_tcezg_6</value>
      <webElementGuid>335e797e-4ee2-44a4-bca4-98852bdea00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toner cho da dầ</value>
      <webElementGuid>d7c4df50-36ec-42cf-9b11-a11d46667324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-textarea-id&quot;)</value>
      <webElementGuid>e4342f1c-8ac9-41a2-ad86-0a9539364b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='base-textarea-id']</value>
      <webElementGuid>18d9c723-4e78-4aa2-a6e5-a4f684f825d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chatSceneContainer']/div[2]/div/div/div/textarea</value>
      <webElementGuid>761f0428-4edd-48d6-b78f-16c6e219ffb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c7c5b1c7-6285-4d38-8a7b-f57da03d5c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'base-textarea-id' and @placeholder = 'Nhập nội dung tin nhắn...' and (text() = 'Toner cho da dầ' or . = 'Toner cho da dầ')]</value>
      <webElementGuid>b6e25e07-77bf-4ea0-9166-4ee1656174c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
