<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Toner cho da du mn th nn dng loi no</name>
   <tag></tag>
   <elementGuidId>eebf34a6-dfe8-441f-b5da-2389278cf194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='base-textarea-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#base-textarea-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2e521580-2b57-432f-85c7-030f0aeb4f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base-textarea-id</value>
      <webElementGuid>c77408a0-875a-4237-9bed-19826ad72076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>5374f730-7d27-4fe9-ac6a-9fd2626ba23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập nội dung tin nhắn...</value>
      <webElementGuid>800c4748-4052-465e-9f73-074fce35f0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_tara_tcezg_6</value>
      <webElementGuid>b567d4b8-bc6a-4d3d-9041-b077589440bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toner cho da dầu mụn thì nên dùng loại nào</value>
      <webElementGuid>04ccfa89-7f87-4aba-b640-7b7b2eb55a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-textarea-id&quot;)</value>
      <webElementGuid>b05512c4-a285-44ad-9d30-c98c66d633b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='base-textarea-id']</value>
      <webElementGuid>0131c441-fe64-498c-a846-0bff7ff76411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chatSceneContainer']/div[2]/div/div/div/textarea</value>
      <webElementGuid>e50a3eb2-4882-4c79-b68f-861e3bd1f227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>00ac39ae-70cf-4164-8311-62442969e23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'base-textarea-id' and @placeholder = 'Nhập nội dung tin nhắn...' and (text() = 'Toner cho da dầu mụn thì nên dùng loại nào' or . = 'Toner cho da dầu mụn thì nên dùng loại nào')]</value>
      <webElementGuid>ef18f4a8-581e-490e-95fa-55d03b155e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
