<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Toner cho da du mn th nn dng</name>
   <tag></tag>
   <elementGuidId>ffac5dd0-e01d-45ac-9a77-b25cc4dfbc4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='base-textarea-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#base-textarea-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2d3697c6-435d-478b-a7fc-e1ddb01673f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base-textarea-id</value>
      <webElementGuid>2fa08427-826b-4799-a8af-6f0f49fa0f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>6ddf165e-23c7-4fed-92d6-9b5b0587a06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập nội dung tin nhắn...</value>
      <webElementGuid>52eb3af8-310c-4a4f-9d2f-9555123f35c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_tara_tcezg_6</value>
      <webElementGuid>6f89f38d-49a4-4edd-84b7-7d0ac67a954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toner cho da dầu mụn thì nên dùng</value>
      <webElementGuid>6ba4ed6d-bd4b-41f9-a702-c4ed99e31adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-textarea-id&quot;)</value>
      <webElementGuid>bb572b7f-cbc1-48a8-977c-2c709be6d2e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='base-textarea-id']</value>
      <webElementGuid>38cb103d-48c3-478f-b45b-673484d6a1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chatSceneContainer']/div[2]/div/div/div/textarea</value>
      <webElementGuid>222cd262-b7b4-4163-a76b-17c25ef3a7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a492650d-7b13-4801-97cc-455c94df6974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'base-textarea-id' and @placeholder = 'Nhập nội dung tin nhắn...' and (text() = 'Toner cho da dầu mụn thì nên dùng' or . = 'Toner cho da dầu mụn thì nên dùng')]</value>
      <webElementGuid>75a1b1e2-0f18-4fa4-864b-8dccf9428d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
