<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Toner cho da du mn t</name>
   <tag></tag>
   <elementGuidId>09875bb9-33ad-4c66-9eeb-cfc685df4d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='base-textarea-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#base-textarea-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a2579da6-0f6c-4d13-84ad-98691b7b3cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base-textarea-id</value>
      <webElementGuid>75fcc16d-2a28-4808-b6fd-b967c91486f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>a7da2172-1b89-48af-b0d3-84c73394a34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập nội dung tin nhắn...</value>
      <webElementGuid>594ed312-4af2-4c7b-8b70-108188d4a033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_tara_tcezg_6</value>
      <webElementGuid>160b5875-5178-4559-b12b-86bd3a676551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toner cho da dầu mụn t</value>
      <webElementGuid>85984105-92f0-43f5-9319-86d6d843f40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base-textarea-id&quot;)</value>
      <webElementGuid>865bca3b-c7b3-4149-ba83-f759133bd217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='base-textarea-id']</value>
      <webElementGuid>af25114c-8111-4c8b-9425-aa644e4c31ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chatSceneContainer']/div[2]/div/div/div/textarea</value>
      <webElementGuid>2b0f1263-9531-497b-8ac3-b4c9a5062cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>88c6c0be-2cef-48ad-bda6-07c13dbd110c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'base-textarea-id' and @placeholder = 'Nhập nội dung tin nhắn...' and (text() = 'Toner cho da dầu mụn t' or . = 'Toner cho da dầu mụn t')]</value>
      <webElementGuid>c7cda35a-4690-46ab-a3b3-110fe9193065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
