<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nonExistAccount</name>
   <tag></tag>
   <elementGuidId>e6976f23-c602-4a78-9f50-786fd3fa2fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._4-u2._1w1t._4-u8._52jv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ceb40140-3c6f-47bf-a4a4-c6c06c4c7cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_4-u2 _1w1t _4-u8 _52jv</value>
      <webElementGuid>ddcc48d2-fca5-4040-84c3-69bcfa15796e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in to FacebookLog inKeep me logged in to hasaki.vnForgotten password?Not now</value>
      <webElementGuid>160e78fa-d939-42c0-b865-ae5cb1dc7903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;_4-u5 _30ny&quot;]/div[@class=&quot;_4-u2 _1w1t _4-u8 _52jv&quot;]</value>
      <webElementGuid>8d41ef54-eb50-4952-9d1a-116fbc943419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div</value>
      <webElementGuid>f92c324f-8f70-40c3-8f80-305bfb9b33da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>3005aa1b-759e-4a99-9a76-5ad329b33644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Log in to FacebookLog inKeep me logged in to hasaki.vnForgotten password?Not now' or . = 'Log in to FacebookLog inKeep me logged in to hasaki.vnForgotten password?Not now')]</value>
      <webElementGuid>2e4ae2d2-204e-4b05-a23d-f0f924b2077b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div</value>
      <webElementGuid>97ba61c1-ebf0-41e8-9529-698691646841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>67223c63-e1be-445b-ad2f-0962e07a84e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
