<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wrongPassword</name>
   <tag></tag>
   <elementGuidId>a4f3dd71-cb85-45cd-9237-16e94966a4af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error_box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error_box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e56418e2-c7b5-4ecc-b284-f3fbfb4c9441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pam _3-95 _9ay3 uiBoxRed</value>
      <webElementGuid>a4415b90-7bd2-4f69-91bf-10061fc5906a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>879b3278-d3a1-4048-95b7-2455c30c896f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d17031ce-8c1b-4ca7-9c80-db3d286a3a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error_box</value>
      <webElementGuid>54dca2d4-5c62-4df5-a515-b26c0bdd9091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You've entered an old passwordYour password was changed about 2 years agoIf you don't remember making this change, click here.</value>
      <webElementGuid>b1ca761d-a44c-423c-914d-24b1f04256b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error_box&quot;)</value>
      <webElementGuid>13fded1f-4978-4bfa-a6ec-384d06a28f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error_box']</value>
      <webElementGuid>c25dfece-1da3-4b63-a9e4-0b757b14106c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div</value>
      <webElementGuid>93a88982-9464-42af-a670-1ee22e412479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>0a2e6648-a975-4874-bd96-c74b5c7b1904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error_box' and (text() = concat(&quot;You&quot; , &quot;'&quot; , &quot;ve entered an old passwordYour password was changed about 2 years agoIf you don&quot; , &quot;'&quot; , &quot;t remember making this change, click here.&quot;) or . = concat(&quot;You&quot; , &quot;'&quot; , &quot;ve entered an old passwordYour password was changed about 2 years agoIf you don&quot; , &quot;'&quot; , &quot;t remember making this change, click here.&quot;))]</value>
      <webElementGuid>51d1f8dc-d719-482a-9274-508f3a390725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
