<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>footer_selector</name>
   <tag></tag>
   <elementGuidId>23998c35-094e-45ce-919d-f9bb7bd68fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.block_top_footer.width_common</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
