<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header</name>
   <tag></tag>
   <elementGuidId>f4a53607-c1e1-49a5-8ccb-01b1863aea7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header_wap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_wap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
