<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cp nht</name>
   <tag></tag>
   <elementGuidId>ea833b42-a8ca-418a-9c9c-1b4ad7a77bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn_site_3.width_common</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-account']/div[3]/div/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b80b4df8-5861-4928-8855-a9f851ea6f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_site_3 width_common</value>
      <webElementGuid>b8ad4ed3-fdfe-43df-b403-a19d8bca5982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cập nhật </value>
      <webElementGuid>714a1bbc-e317-4b6d-9699-333c092d3c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-account&quot;)/div[@class=&quot;content_box_profile_page&quot;]/div[@class=&quot;relative width_common block_input_account&quot;]/div[@class=&quot;form-group row space_bottom_20&quot;]/div[@class=&quot;col-lg-5&quot;]/button[@class=&quot;btn btn_site_3 width_common&quot;]</value>
      <webElementGuid>92ca7b7d-e6bf-43b4-b8eb-90b484c077bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[3]/div/div[3]/div[2]/button</value>
      <webElementGuid>fbc5f036-1906-4e1d-b576-2ce99e314a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>1eb9d6e7-f6cf-427a-ab09-b3381706764d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Cập nhật ' or . = ' Cập nhật ')]</value>
      <webElementGuid>5bcf9954-087a-4d3c-8d7e-932b827de8de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
