<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S in thoi ca bn  c ng k. Vui lng s dng _d727da</name>
   <tag></tag>
   <elementGuidId>318ad2d0-29b2-494b-b024-133be262a860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-danger.flashSession</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-account']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7476b4bd-5bf3-4658-bad7-97692a74c910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger flashSession</value>
      <webElementGuid>0c88ea30-85f7-4868-98b6-0eb77e13b400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Số điện thoại của bạn đã được đăng kí. Vui lòng sử dụng số điện thoại khác.</value>
      <webElementGuid>ac4eac43-871d-47f9-8f7f-3a4306f54146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-account&quot;)/div[@class=&quot;alert alert-danger flashSession&quot;]</value>
      <webElementGuid>dd5a9bfd-9149-413e-b094-67a31e7b8e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]</value>
      <webElementGuid>990c9170-62ff-4b0c-b468-7ebb95059d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/form/div[2]</value>
      <webElementGuid>9e446a1f-5f8a-4d5c-8e4d-0c51087d9222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Số điện thoại của bạn đã được đăng kí. Vui lòng sử dụng số điện thoại khác.' or . = 'Số điện thoại của bạn đã được đăng kí. Vui lòng sử dụng số điện thoại khác.')]</value>
      <webElementGuid>76827301-da7d-482f-bf57-3ea85aca562a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
