<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_S in thoi khng hp l</name>
   <tag></tag>
   <elementGuidId>903d327b-1083-493f-9a88-61587e24d856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='phone-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a75ce8d0-9ad1-4ff6-bf0a-027cc3ba09b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-error</value>
      <webElementGuid>ad572286-7eb1-4d35-86c3-6e16e2858d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>79569d66-a7ee-4f8c-8f05-7dfa60482373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Số điện thoại không hợp lệ.</value>
      <webElementGuid>4e683b0e-09fd-4ebf-b562-31fd21057fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-error&quot;)</value>
      <webElementGuid>bd21fc38-0873-46fb-99c5-ab1e4645a043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='phone-error']</value>
      <webElementGuid>08ba9d04-bdaa-4fa9-9602-cfa5d52adeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div/div[2]/span</value>
      <webElementGuid>d3264cba-07c1-4e99-aed3-7a3736f8371f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span</value>
      <webElementGuid>34c1b684-e40d-4a01-aa2e-afe6412306c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'phone-error' and (text() = 'Số điện thoại không hợp lệ.' or . = 'Số điện thoại không hợp lệ.')]</value>
      <webElementGuid>cf72c7de-b183-4a48-bb44-549439c96ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
