<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thng tin bt buc</name>
   <tag></tag>
   <elementGuidId>a568360a-5632-4849-81f0-3a76a8fff928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='phone-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61e7889b-5b37-4c9a-b7fe-948c860c170f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-error</value>
      <webElementGuid>e84d6c85-4126-4369-8017-64b5609f5842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>c92f5c90-8c70-4f79-940d-1d8421d43dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin bắt buộc.</value>
      <webElementGuid>64e035d8-58c5-40ec-b918-376a8d817833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-error&quot;)</value>
      <webElementGuid>a57ca02c-4fab-48f3-94e7-2838a27422d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='phone-error']</value>
      <webElementGuid>453454f1-7239-49e8-bd59-29377d5f7bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div/div[2]/span</value>
      <webElementGuid>128e3b88-0962-4e71-a32b-f196ea36d005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span</value>
      <webElementGuid>e7ed9d08-d166-4649-8c99-6b8dcc3186cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'phone-error' and (text() = 'Thông tin bắt buộc.' or . = 'Thông tin bắt buộc.')]</value>
      <webElementGuid>21b1a8ba-d784-49d0-bb44-fa9fda1294bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
