<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chnh sa</name>
   <tag></tag>
   <elementGuidId>43421bc6-3473-40c1-bce6-8d70c7597dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.txt_color_1.txt_xemthem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box_thongtin_account']/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0d271ae-ecf5-4421-8eee-05009e2e864c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt_color_1 txt_xemthem</value>
      <webElementGuid>2a932dc4-7d7c-4a3a-b4ae-fc1decb4baa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hasaki.vn/customer/account/edit/</value>
      <webElementGuid>fb4d151d-5e55-4f2d-9c65-3c6e68cb9317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chỉnh sửa</value>
      <webElementGuid>9304db95-5b45-40fd-a630-0dc379b4a9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box_thongtin_account&quot;)/div[@class=&quot;content_box_profile_page&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-xs-6&quot;]/div[@class=&quot;block_thongtin_account width_common relative&quot;]/a[@class=&quot;txt_color_1 txt_xemthem&quot;]</value>
      <webElementGuid>cbad3e3e-bda9-47e5-a415-106d5d7f09be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box_thongtin_account']/div[2]/div/div/div/a</value>
      <webElementGuid>9a349d34-9a20-4855-9cd7-550614ab0a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Chỉnh sửa')])[2]</value>
      <webElementGuid>9010a659-16dd-47c7-8ff6-9ffe19dfd780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://hasaki.vn/customer/account/edit/')])[2]</value>
      <webElementGuid>a7faabba-3d26-419c-8bae-4d3c35ecee26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>a5bc65f0-1aac-4fba-a6cd-23f75c390af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hasaki.vn/customer/account/edit/' and (text() = 'Chỉnh sửa' or . = 'Chỉnh sửa')]</value>
      <webElementGuid>fa18938a-bfd0-400d-afa2-856bd288cad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
