<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Retinol</name>
   <tag></tag>
   <elementGuidId>86527033-2eff-4fbd-84cb-8ce5b96c450c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_mini_form']/div/a[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3697c05e-96d5-489b-adf5-43d1796da9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hasaki.vn/tag/retinol.html?utm_medium=seo&amp;utm_source=top_keyword&amp;utm_campaign=Retinol_push_18072022</value>
      <webElementGuid>03419437-1f0a-4cfd-b22c-093c9e21d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Retinol</value>
      <webElementGuid>bf8d48d4-f2a8-4633-bcab-923ee0a26847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_mini_form&quot;)/div[@class=&quot;block_demo_search width_common&quot;]/a[6]</value>
      <webElementGuid>89675b6c-e299-4013-9f51-f81d57c1a89d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div/a[6]</value>
      <webElementGuid>caa1a302-f06e-40fc-8287-ab3bedc94c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Retinol')]</value>
      <webElementGuid>90d7f525-8916-45bb-bae4-0d074f397cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hasaki.vn/tag/retinol.html?utm_medium=seo&amp;utm_source=top_keyword&amp;utm_campaign=Retinol_push_18072022')]</value>
      <webElementGuid>cd0192ae-f831-4ae0-8f60-1f1f928b1575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>c825bf78-bf5a-4e0d-9e64-5f00c67f6bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hasaki.vn/tag/retinol.html?utm_medium=seo&amp;utm_source=top_keyword&amp;utm_campaign=Retinol_push_18072022' and (text() = 'Retinol' or . = 'Retinol')]</value>
      <webElementGuid>e30ef75a-3e3f-4791-ab38-a582c67e8515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
