<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ty t bo cht</name>
   <tag></tag>
   <elementGuidId>e7ab5a52-987a-48c5-956e-3dc699b7dfe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_mini_form']/div/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>413a04cc-ecf5-4f2c-80f4-fa800e22c395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hasaki.vn/danh-muc/tay-te-bao-chet-da-mat-c35.html?utm_medium=seo&amp;utm_source=top_keyword&amp;utm_campaign=taytebaochet_push_29032022</value>
      <webElementGuid>57e619a7-0691-4d26-9b0d-c2eea2e30b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tẩy tế bào chết</value>
      <webElementGuid>e30d1127-3083-4256-9b36-a77ea239d6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_mini_form&quot;)/div[@class=&quot;block_demo_search width_common&quot;]/a[5]</value>
      <webElementGuid>b919bf26-48ec-4a0d-bc6e-d2f9760db599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div/a[5]</value>
      <webElementGuid>24cf4f49-1340-4b5b-ba88-910c176f3331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tẩy tế bào chết')]</value>
      <webElementGuid>cbd102c3-06c8-4cdd-9df8-4f21215692c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hasaki.vn/danh-muc/tay-te-bao-chet-da-mat-c35.html?utm_medium=seo&amp;utm_source=top_keyword&amp;utm_campaign=taytebaochet_push_29032022')]</value>
      <webElementGuid>0708222b-f25e-4321-9cd3-71f9e4a9f976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>055f0074-ade4-4f98-9854-5657d5d4cd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hasaki.vn/danh-muc/tay-te-bao-chet-da-mat-c35.html?utm_medium=seo&amp;utm_source=top_keyword&amp;utm_campaign=taytebaochet_push_29032022' and (text() = 'Tẩy tế bào chết' or . = 'Tẩy tế bào chết')]</value>
      <webElementGuid>e9b3c8d7-c842-4ca4-8a05-1f7840c023f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
