<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider</name>
   <tag></tag>
   <elementGuidId>a4749454-93c3-41b6-a775-dec9cd1c6519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='flex-active-slide']//img[@alt='#']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.lazy.loaded[data-src='https://media.hcdn.vn/hsk/1702463977846x250home-16.jpg']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
