<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ti nh ca bn</name>
   <tag></tag>
   <elementGuidId>029ec35e-485d-47d5-90b0-334d013453bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loadImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='loadImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>738bde61-70fa-4a80-b57d-e405588ff562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>37f5331a-b06f-432f-8d2b-4fb93bf4af82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt_color_1</value>
      <webElementGuid>1f2dc2c4-8cc8-4e31-ad59-6b7304937ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loadImg</value>
      <webElementGuid>9017de6d-bc52-48f0-8455-7902caa86c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tải ảnh của bạn</value>
      <webElementGuid>2defbdb2-e063-4b36-b375-82633e18aa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loadImg&quot;)</value>
      <webElementGuid>2b33bae3-eb34-4dd9-95f4-52daebd747a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='loadImg']</value>
      <webElementGuid>e25fc746-7464-4b03-af62-65b1252f0404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div/a</value>
      <webElementGuid>e104a56a-5f2d-4dbd-b2fb-01fb84db84bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tải ảnh của bạn')]</value>
      <webElementGuid>30798343-04a6-4aa0-929f-00f42742c649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>ff3b6bdb-1b85-4ee8-83c9-f2b4df440e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/a</value>
      <webElementGuid>60b0a84c-d22e-4a45-bf12-535e2d898ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'loadImg' and (text() = 'Tải ảnh của bạn' or . = 'Tải ảnh của bạn')]</value>
      <webElementGuid>9e73e827-8f70-45a3-99ea-e4d5ab42afaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
