<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cp nht</name>
   <tag></tag>
   <elementGuidId>54b3e836-92f0-4834-803f-f8d018507f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-12 > button.btn.btn_site_1.width_common</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8fa6b0e2-660d-40a5-a78a-8c951a9c7f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5fe148e6-6405-45ad-a078-9ee0e16dc180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn_site_1 width_common</value>
      <webElementGuid>63d9c390-4063-48c5-a011-5bfe2dd7d426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cập nhật</value>
      <webElementGuid>707f4667-cd4a-451a-8b8e-390f320e4a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-account&quot;)/div[@class=&quot;content_box_profile_page&quot;]/div[@class=&quot;relative width_common block_input_account&quot;]/div[@class=&quot;main_input_info_account&quot;]/div[@class=&quot;col-lg-12&quot;]/button[@class=&quot;btn btn_site_1 width_common&quot;]</value>
      <webElementGuid>301a5fa3-01ce-4ba4-a776-9b6a0fe085b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>5c72779e-915c-4774-811c-c9514500b0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div[2]/div[9]/button</value>
      <webElementGuid>b4fcb072-28aa-4eeb-ab56-1f30f719dc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>8b232b1d-8d2d-4f59-bc1d-ac6b4e83f8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Cập nhật' or . = 'Cập nhật')]</value>
      <webElementGuid>715c20bd-7570-4ec9-a483-9634987932a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
