<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgavatarImg</name>
   <tag></tag>
   <elementGuidId>5a0c53ce-96a6-43ee-a0d7-408c416f47b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avatarImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='avatarImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8814cb21-f302-4319-8b0a-666b868734c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hasaki.vn/images/graphics/account-full.svg</value>
      <webElementGuid>54b43518-4b57-4c7f-8894-8dd45af7b16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>avatarImg</value>
      <webElementGuid>f823c80a-d13b-487c-99cf-68ecc1248f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>efd7b144-cd73-4467-a906-8a6e9d041287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f586b0b2-7fb6-4765-a7cd-0eebab89d228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avatarImg&quot;)</value>
      <webElementGuid>1d66c2a8-8ed1-4891-8f72-323629957901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='avatarImg']</value>
      <webElementGuid>26d182a8-67b6-4d4a-90f2-f1baa839cffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div/div/img</value>
      <webElementGuid>1cd2e51f-6b2e-4f7e-8b0b-6b316fb344ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://hasaki.vn/images/graphics/account-full.svg')])[2]</value>
      <webElementGuid>1ee543d1-bcaa-4839-8215-c21b8f59dde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/img</value>
      <webElementGuid>2179bfb9-f56b-42f0-b93c-a40968882f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/images/graphics/account-full.svg' and @id = 'avatarImg']</value>
      <webElementGuid>911154e4-ef1a-4750-bcef-f42ea5d11aa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
