<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>connect_selector</name>
   <tag></tag>
   <elementGuidId>28a7eeb6-990c-44f0-8d13-489cdd1c14f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>._notify_71j4u_1&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
