<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passwordNew</name>
   <tag></tag>
   <elementGuidId>90589884-f6fa-470f-af85-f0f80ec8a257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bc234ae-6f0b-42eb-8fd9-267c5e9ed896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f522a3dc-1e7d-481d-9c8b-0962e6b6ded6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a01d7443-ce61-4fee-b8fe-00b3cafb146f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordNew</value>
      <webElementGuid>db8397cf-422c-472b-b7e9-b9cdbd7e6662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwordNew</value>
      <webElementGuid>434b46a0-dac8-4a95-9295-06e731fea7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu từ 6 đến 32 ký tự</value>
      <webElementGuid>5faabcf2-938e-4283-a73c-ef1bdd44ee9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordNew&quot;)</value>
      <webElementGuid>99cc310c-e189-4cdc-8887-5204a1f2e48c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordNew']</value>
      <webElementGuid>37dcce7b-ee46-471d-8307-d7fd825eba02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div[2]/input</value>
      <webElementGuid>43718a80-41f8-406c-8dec-d53479e3ca25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e5463c1d-1776-4350-83a1-6f6d9f8b6270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'passwordNew' and @name = 'passwordNew' and @placeholder = 'Mật khẩu từ 6 đến 32 ký tự']</value>
      <webElementGuid>c9c415c8-98a5-4c3a-95aa-c7d4ca47530b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
