<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passwordConfirm</name>
   <tag></tag>
   <elementGuidId>4a791b62-7923-4eb3-93b9-f9f23b8234b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdeefada-fb22-48df-ae20-1feead0edd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>94bd5f40-ea54-4372-8e85-0b4b01e402c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2869edab-b7da-4736-b5d2-08a849c72156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordConfirm</value>
      <webElementGuid>c16a5d80-4394-4eb9-bbf8-1a9909154c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwordConfirm</value>
      <webElementGuid>a96d015f-6817-42a5-bf99-df4250a9a518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập lại mật khẩu mới</value>
      <webElementGuid>65a025cb-80a1-4d73-a9c1-276c90a5ea22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordConfirm&quot;)</value>
      <webElementGuid>2848f840-bbf7-45d7-9eb9-b666ca890572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordConfirm']</value>
      <webElementGuid>d58310ef-f175-4d9c-a9ec-c4b2341ea603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div[3]/input</value>
      <webElementGuid>6f2b7528-226f-41ad-abb4-a44fc974c355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>bca0cbf0-3d77-4ca6-a0b4-62740bba8034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'passwordConfirm' and @name = 'passwordConfirm' and @placeholder = 'Nhập lại mật khẩu mới']</value>
      <webElementGuid>2889d813-73d9-4cd1-93c9-312b5ddcf3c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
