<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mt khu khng trng khp</name>
   <tag></tag>
   <elementGuidId>868182f3-49a9-4f4e-a635-7f5f694ddf04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordConfirm-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='passwordConfirm-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e0877ac-9eda-4c3a-88c2-54cf291354a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordConfirm-error</value>
      <webElementGuid>012c1f25-0414-44ca-9514-c04819601991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>bb88e806-ed69-4d42-8984-775157bb32b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mật khẩu không trùng khớp</value>
      <webElementGuid>126536c9-77ba-4b43-9e6c-d80671a81c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordConfirm-error&quot;)</value>
      <webElementGuid>438afc3e-7866-439c-9020-62eaa91c156c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='passwordConfirm-error']</value>
      <webElementGuid>1b2778e5-7790-442e-a3be-e40912e2455e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[3]/div/div[3]/span</value>
      <webElementGuid>7259c62d-e0ff-469f-ae87-6890fabe7bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>89f5c1f2-cf3e-4c5f-8190-5ba379178b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'passwordConfirm-error' and (text() = 'Mật khẩu không trùng khớp' or . = 'Mật khẩu không trùng khớp')]</value>
      <webElementGuid>294785b5-7ef4-421d-8452-b113bbc570a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
