<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thng tin bt buc</name>
   <tag></tag>
   <elementGuidId>82b10e2f-5eec-4501-9ac8-168cd4902fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordNew-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='passwordNew-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0bc812f-90a1-4f7c-8c19-51d1ba4d17d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordNew-error</value>
      <webElementGuid>92485f7a-1f63-4a55-84c8-43701fabc918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>3df257a5-5b30-4332-8859-3ce4092c336b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin bắt buộc.</value>
      <webElementGuid>9e2318a0-c4ec-4b16-9856-ea3b08a8200f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordNew-error&quot;)</value>
      <webElementGuid>86a64c1a-31a3-4d04-b986-7f98f22b7509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='passwordNew-error']</value>
      <webElementGuid>a8e08222-2dd1-4b6d-9054-60298491b199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div[2]/span</value>
      <webElementGuid>f29440a2-4563-4564-97cc-2467ba9efc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>ee08162c-61cc-4a70-a22a-1553d87d56e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'passwordNew-error' and (text() = 'Thông tin bắt buộc.' or . = 'Thông tin bắt buộc.')]</value>
      <webElementGuid>f34e32af-01a4-46f7-9456-a972aa7d5308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
